#!/bin/sh

CONF_DIR=/var/lib/connman
if [ ! -d ${CONF_DIR} ]; then
    mkdir -p ${CONF_DIR} || true
fi

if [ ! -e /var/run/dbus/system_bus_socket ] ; then
    mkdir -p /var/run/dbus
    ln -s /usr/local/var/run/dbus/system_bus_socket /var/run/dbus/system_bus_socket
fi

nfsroot=0

exec 9<&0 < /proc/mounts
while read dev mtpt fstype rest; do
	if test $mtpt = "/" ; then
		case $fstype in
		    nfs | nfs4)
			nfsroot=1
			break
			;;
		    *)
			;;
		esac
	fi
done

if test $nfsroot -eq 1 ; then
	CONFIGF=/var/lib/connman/wired.config

	# Extract wired network config from /proc/cmdline
	ipinfo=`cat /proc/cmdline |grep -o ' ip=[^ ]*'`
	hostip=`ip addr show dev eth0 | grep -m 1 inet | cut -d/ -f 1 | cut -d"t" -f 2`
	gatewayip=`echo $ipinfo | cut -d: -f 3`
	dnsip=`echo $ipinfo | cut -d: -f 2`
	netmask=`ip addr show dev eth0 | grep -m 1 inet | cut -d/ -f 2 | cut -d" " -f 1`
	macaddr=`ifconfig eth0 | grep -o 'HWaddr [^ ]*' | cut -d' ' -f 2`

	# Setup a connman config accordingly
	if [ ! -f ${CONFIGF} ] ; then
	    echo "[service_ethernet]" >> ${CONFIGF}
	    echo "Type = ethernet"  >> ${CONFIGF}
	    echo "IPv4 =" >> ${CONFIGF}
	    echo "MAC =" >> ${CONFIGF}
	    echo "Nameservers =" >> ${CONFIGF}
	fi
	sed -i -e "s|^IPv4 =.*|IPv4 = ${hostip}/${netmask}/${gatewayip}|" ${CONFIGF}
	sed -i -e "s|^MAC =.*|MAC = ${macaddr}|" ${CONFIGF}
	sed -i -e "s|^Nameservers =.*|Nameservers = ${dnsip}|" ${CONFIGF}

	# Tell connman to ignore eth0 interface on device cleanup so the existing NFS
	# configuration stays as it is
	systemctl set-environment CONNMAN_IGNORE_IFACE_ON_CLEANUP=eth0
fi
