# Copyright (c) 2022-2025 LG Electronics, Inc.

EXTENDPRAUTO:append = "webos1"

# Needed for armnn linking with static flatbuffers
# http://gecko.lge.com/Errors/Details/433271
# FAILED: libarmnnTfLiteParser.so.24.3
# : && TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/recipe-sysroot-native/usr/bin/arm-oemllib32-linux-gnueabi/arm-oemllib32-linux-gnueabi-g++ -fPIC -mthumb -mfpu=neon -mfloat-abi=softfp -mcpu=cortex-a9 -mtune=cortex-a9 -funwind-tables -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/lib32-recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2=/usr/src/debug/lib32-armnn/21.11-r2                      -fdebug-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2=/usr/src/debug/lib32-armnn/21.11-r2                      -fdebug-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/lib32-recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/recipe-sysroot-native=  -fvisibility-inlines-hidden  -fopenmp -ITOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/lib32-recipe-sysroot/usr -Wno-error=array-bounds -Wno-error=deprecated-declarations -std=c++14 -Wall -Wextra -Werror -Wold-style-cast -Wno-missing-braces -Wconversion -Wsign-conversion  -Wno-psabi -DNDEBUG -DNDEBUG -O3  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2=/usr/src/debug/lib32-armnn/21.11-r2                      -fdebug-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2=/usr/src/debug/lib32-armnn/21.11-r2                      -fdebug-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/lib32-recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/recipe-sysroot-native=  -Wl,-z,relro,-z,now -shared -Wl,-soname,libarmnnTfLiteParser.so.24 -o libarmnnTfLiteParser.so.24.3 src/armnnTfLiteParser/CMakeFiles/armnnTfLiteParser.dir/TfLiteParser.cpp.o  -Wl,-rpath,"\$ORIGIN:"  -L/opencl-1.2-stubs  libarmnn.so.27.0  -Wl,-Bstatic  -lflatbuffers  libarmnnUtils.a  libarmnnTestUtils.a  profiling/common/src/libpipeCommon.a  -Wl,-Bdynamic  -ldl  third-party/fmt/libfmt.a  -L/opencl-1.2-stubs  -Wl,-Bstatic  -larm_compute_core-static  -larm_compute-static  -larm_compute_core-static  -larm_compute-static  -Wl,-Bdynamic && :
# TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/recipe-sysroot-native/usr/bin/arm-oemllib32-linux-gnueabi/../../libexec/arm-oemllib32-linux-gnueabi/gcc/arm-oemllib32-linux-gnueabi/12.1.0/ld: error: TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/lib32-recipe-sysroot/usr/lib/libflatbuffers.a(util.cpp.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
# TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/recipe-sysroot-native/usr/bin/arm-oemllib32-linux-gnueabi/../../libexec/arm-oemllib32-linux-gnueabi/gcc/arm-oemllib32-linux-gnueabi/12.1.0/ld: error: TOPDIR/BUILD/work/mach-oemllib32-linux-gnueabi/lib32-armnn/21.11-r2/lib32-recipe-sysroot/usr/lib/libflatbuffers.a(util.cpp.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
# collect2: error: ld returned 1 exit status
CXXFLAGS += "-fPIC"
